apiVersion: batch/v1
kind: Job
metadata:
  name: telemetrygen-normal
  namespace: otel-tst
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telemetrygen-normal
      annotations:
        sidecar.istio.io/proxyCPU: "300m"
        sidecar.istio.io/proxyMemory: "1024Mi"
    spec:
      restartPolicy: Never
      containers:
      - name: telemetrygen
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.126.0
        args:
        - traces
        - --otlp-endpoint=opentelemetry-main-collector.otel-tst.svc.cluster.local:4317
        - --otlp-insecure
        - --traces=100
        - --child-spans=14
        - --status-code=ok
        - --service=load-test-normal-service
        resources:
          requests:
            cpu: 150m
            memory: 384Mi
          limits:
            cpu: 300m
            memory: 768Mi
      imagePullSecrets:
      - name: ghcr-auth